version: '3'
services:
  proto:
    container_name: proto
    command: ./proto/scripts/protoc.sh
    build:
      context: .
      dockerfile: DockerfileProto
    volumes:
      - .:/proto
  server:
    container_name: server
    build:
      context: .
      dockerfile: DockerfileServer
    volumes:
      - ./server:/go/src
    ports:
      - "9090:9090"
    command: ["air"]
    depends_on:
      - proto
  mysql:
    image: mysql:5.7
    build: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data 
      MYSQL_USER: root 
      MYSQL_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_volume:/var/lib/mysql
    depends_on:
      - server
  envoy:
    container_name: envoy
    build:
      context: .
      dockerfile: DockerfileEnvoy
    ports:
      - "8080:8080"
    links:
      - server
  client:
    container_name: client 
    command: ./scripts/client.sh
    build:
      context: .
      dockerfile: DockerfileClient
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - proto
    ports:
      - "3000:3000"
    environment: 
      - EXTEND_ESLINT=true
